version: "3.9"
services:
  nginxapp:
    #container_name: mywebapp
    image: dockerwebapp:1.0
    labels: 
      - frontendapp
      - dockerwebapp
    deploy:
      replicas: 1
    expose:
      - "8080"
    ports:
      - "8080:80"
      - "8443:443"

# docker-compose -f docker-nginx.yaml -p dockerwebapp up
# 
